'use strict';
/* gen-nginx.js — render hosting/nginx/digcit.conf from digcit.conf.template,
   substituting __DOMAIN__ with the host from SITE_URL (see config.js). Keeps the
   deploy domain in ONE place shared with the page generators.
   Run: SITE_URL=https://breakouts.yourdistrict.org node scripts/gen-nginx.js */
const fs = require('fs');
const path = require('path');
const { SITE_URL } = require('./config');

const DOMAIN = new URL(SITE_URL).hostname;
const dir = path.join(__dirname, '..', 'hosting', 'nginx');
const tpl = fs.readFileSync(path.join(dir, 'digcit.conf.template'), 'utf8');
const out = tpl
  .replace(/^# nginx site config TEMPLATE /, '# nginx site config (GENERATED by scripts/gen-nginx.js — edit the .template) ')
  .replace(/\n# Do not edit digcit\.conf by hand[\s\S]*?the page generators\.\n#\n/, '\n')
  .replace(/__DOMAIN__/g, DOMAIN);
fs.writeFileSync(path.join(dir, 'digcit.conf'), out);
console.log('wrote hosting/nginx/digcit.conf  (server_name = ' + DOMAIN + ')');
